# Generated by Django 4.2.11 on 2024-04-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 일시')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시')),
                ('name', models.CharField(max_length=100, verbose_name='상품 이름')),
                ('content', models.CharField(max_length=100, verbose_name='상품 내용')),
                ('sale_started_at', models.DateTimeField(blank=True, null=True, verbose_name='판매 시작 시각')),
                ('sale_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='판매 종료 시각')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='상품 금액')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='할인 금액')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품들',
            },
        ),
    ]
