# Generated by Django 4.2.11 on 2024-04-11 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_category_productcategory_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='재고 양')),
                ('prodcut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.product')),
            ],
            options={
                'verbose_name': '상품재고',
            },
        ),
    ]
